"""Unit tests for the `dbc2codec` compiler itself.

Covers provenance header, schema validation, deterministic output, and the
documented skip rules (multiplexed signals) plus the v0.3.0 sawtooth support
for multi-byte Motorola signals.

Requirements traced: SYS-FR-018, QA-v0.2-R01 (and QA-H02 via test_parity.py).
"""

from __future__ import annotations

import sys
from pathlib import Path

import pytest
import yaml

HERE = Path(__file__).resolve().parent
REPO_ROOT = HERE.parents[2]
sys.path.insert(0, str(REPO_ROOT / "tools" / "dbc2codec"))

import dbc2codec  # noqa: E402


SAMPLE_DBC = """\
VERSION ""

BO_ 512 Example: 8 Vector__XXX
 SG_ LittleU16 : 0|16@1+ (0.25,0) [0|16383.75] "rpm" Vector__XXX
 SG_ MotorolaByte : 23|8@0- (1,-40) [-128|127] "degC" Vector__XXX
 SG_ Flag : 24|1@1+ (1,0) [0|1] "" Vector__XXX
 SG_ MultiMotorola : 31|12@0+ (1,0) [0|4095] "" Vector__XXX
 SG_ Multiplexer M : 32|2@1+ (1,0) [0|3] "" Vector__XXX
 SG_ Muxed m1 : 34|4@1+ (1,0) [0|15] "" Vector__XXX

VAL_ 512 Flag 1 "SET" 0 "CLEAR" ;
"""


def load_doc(dbc_text: str, name: str = "example"):
    db = dbc2codec.DbcDatabase.load(dbc_text)
    doc, _warnings = dbc2codec.build_codec_map(db, name, "1.0.0")
    return doc


def test_provenance_header_present(run_dbc2codec, tmp_path: Path):
    dbc = tmp_path / "sample.dbc"
    dbc.write_text(SAMPLE_DBC)
    out, _ = run_dbc2codec(dbc, "example")
    text = out.read_text()
    assert "# GENERATED BY: dbc2codec v" in text
    assert "# SOURCE: https://github.com/commaai/opendbc" in text
    assert "# COMMIT: pinned" in text
    assert "# LICENSE: MIT (Copyright (c) comma.ai)" in text


def test_output_validates_against_schema(run_dbc2codec, tmp_path: Path):
    dbc = tmp_path / "sample.dbc"
    dbc.write_text(SAMPLE_DBC)
    out, _ = run_dbc2codec(dbc, "example")
    # run_dbc2codec already validated with jsonschema; additionally check the
    # YAML parses back to the expected structure.
    doc = yaml.safe_load(out.read_text())
    assert doc["schema_version"] == "0.2.0"
    assert doc["codec_map"]["name"] == "example"


def test_multiplexed_signals_skipped(tmp_path: Path):
    doc = load_doc(SAMPLE_DBC)
    names = [s["name"] for m in doc["codec_map"]["messages"] for s in m["signals"]]
    assert "Multiplexer" not in names
    assert "Muxed" not in names
    assert "LittleU16" in names


def test_multi_byte_motorola_skipped(tmp_path: Path):
    # v0.3.0: multi-byte Motorola is now representable with layout sawtooth
    doc = load_doc(SAMPLE_DBC)
    names = [s["name"] for m in doc["codec_map"]["messages"] for s in m["signals"]]
    assert "MultiMotorola" in names
    # single-byte Motorola remains representable (contiguous and sawtooth are identical there)
    assert "MotorolaByte" in names
    sigs = {s["name"]: s for m in doc["codec_map"]["messages"] for s in m["signals"]}
    multi = sigs["MultiMotorola"]
    assert multi["endianness"] == "big"
    assert multi["bit_length"] == 12
    assert multi["start_bit"] == 31
    assert multi.get("layout") == "sawtooth"
    # Contiguous single-byte should not need explicit layout (defaults to contiguous)
    assert sigs["MotorolaByte"].get("layout", "contiguous") == "contiguous"


def test_endianness_and_signed_mapping(tmp_path: Path):
    doc = load_doc(SAMPLE_DBC)
    sigs = {s["name"]: s for m in doc["codec_map"]["messages"] for s in m["signals"]}
    le = sigs["LittleU16"]
    assert le["endianness"] == "little"
    assert le["start_bit"] == 0
    assert le["bit_length"] == 16
    assert le["type"] == "uint"
    assert le["scale"] == 0.25

    be = sigs["MotorolaByte"]
    assert be["endianness"] == "big"
    assert be["type"] == "int"
    assert be["offset"] == -40


def test_value_mapping_and_boolean(tmp_path: Path):
    doc = load_doc(SAMPLE_DBC)
    sigs = {s["name"]: s for m in doc["codec_map"]["messages"] for s in m["signals"]}
    assert sigs["Flag"]["type"] == "boolean"
    assert sigs["Flag"]["values"] == {"1": "SET", "0": "CLEAR"}


def test_duplicate_signal_name_skipped(tmp_path: Path):
    dbc = (
        "BO_ 256 A: 8 X\n SG_ Dup : 0|8@1+ (1,0) [0|255] \"\" X\n"
        "BO_ 257 B: 8 X\n SG_ Dup : 0|8@1+ (1,0) [0|255] \"\" X\n"
    )
    db = dbc2codec.DbcDatabase.load(dbc)
    doc, warnings = dbc2codec.build_codec_map(db, "dup", "1.0.0")
    names = [s["name"] for m in doc["codec_map"]["messages"] for s in m["signals"]]
    assert names == ["Dup"]
    assert any("duplicate signal name" in w for w in warnings)


def test_deterministic_output(tmp_path: Path):
    db = dbc2codec.DbcDatabase.load(SAMPLE_DBC)
    doc1, _ = dbc2codec.build_codec_map(db, "example", "1.0.0")
    db2 = dbc2codec.DbcDatabase.load(SAMPLE_DBC)
    doc2, _ = dbc2codec.build_codec_map(db2, "example", "1.0.0")
    rendered1 = dbc2codec.render(doc1, {
        "version": dbc2codec.__version__, "source_url": "u",
        "commit": "c", "license": "l",
    })
    rendered2 = dbc2codec.render(doc2, {
        "version": dbc2codec.__version__, "source_url": "u",
        "commit": "c", "license": "l",
    })
    assert rendered1 == rendered2
