"""In-process CLI tests for yaml2c and its schema gate (issue #22).

Running ``main()`` directly (not via subprocess) both pins the exit-code
contract and covers the CLI code paths for the 100% coverage requirement.

Requirements traced: SW-FR-TOOL-001..005.
Test ids: YAML2C-CLI-001..004.
"""

from __future__ import annotations

import json

import pytest

from tools.trace_viewer import trace_format as tf  # noqa: F401  (import time)
from tools.yaml2c import schema
from tools.yaml2c import yaml2c as cli
from tools.yaml2c.common import Yaml2cError

from conftest import SCHEMA_DIR

FSM_YAML = """
schema_version: "0.3.0"
state_machines:
  - name: m
    initial: s
    states:
      - name: s
instances:
  - id: one
    machine: m
    enabled: true
"""


@pytest.fixture()
def fsm_file(tmp_path):
    path = tmp_path / "doc.yaml"
    path.write_text(FSM_YAML, encoding="utf-8")
    return path


def test_cli_writes_a_file_and_the_banner(fsm_file, tmp_path, capsys):
    output = tmp_path / "sub" / "doc.h"
    code = cli.main(["--schema-dir", str(SCHEMA_DIR), "-o", str(output),
                     str(fsm_file)])
    assert code == 0
    text = output.read_text(encoding="utf-8")
    assert "Generated by CANcestry yaml2c" in text
    assert "#ifndef DOC_FSM_SET_H" in text
    assert "doc_fsm_set" in text


def test_cli_stdout_and_set_symbol(fsm_file, capsys):
    code = cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     "--set-symbol", "custom", str(fsm_file)])
    assert code == 0
    assert "custom_fsm_set" in capsys.readouterr().out


def test_cli_version_flag(fsm_file, capsys):
    with pytest.raises(SystemExit) as info:
        cli.main(["--version"])
    assert info.value.code == 0
    assert cli.__version__ in capsys.readouterr().out


def test_cli_usage_errors_exit_two(fsm_file):
    with pytest.raises(SystemExit) as info:
        cli.main([str(fsm_file), "--bogus"])
    assert info.value.code == 2
    assert cli.main([str(fsm_file.parent / "missing.yaml")]) == 2


def test_cli_document_errors_exit_one(tmp_path, capsys):
    bad = tmp_path / "bad.yaml"
    bad.write_text("schema_version: \"0.3.0\"\nstate_machines: []\n",
                   encoding="utf-8")
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(bad)]) == 1
    assert "yaml2c" in capsys.readouterr().err

    syntax = tmp_path / "syntax.yaml"
    syntax.write_text("a: [1\nb: 2", encoding="utf-8")
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(syntax)]) == 1
    assert "YAML syntax error" in capsys.readouterr().err


def test_cli_kind_mismatch_and_override(fsm_file, capsys):
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--kind", "codec",
                     "--stdout", str(fsm_file)]) == 1
    assert "codec-map" in capsys.readouterr().err
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--kind", "fsm",
                     "--stdout", str(fsm_file)]) == 0


def test_cli_no_schema_validate(tmp_path, capsys):
    old = tmp_path / "old.yaml"
    old.write_text(FSM_YAML.replace('"0.3.0"', '"0.2.0"', 1),
                   encoding="utf-8")
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(old)]) == 1
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     "--no-schema-validate", str(old)]) == 0


def test_cli_missing_schema_dir(tmp_path, fsm_file, capsys):
    code = cli.main(["--schema-dir", str(tmp_path / "nowhere"),
                     "--kind", "fsm", "--stdout", str(fsm_file)])
    assert code == 1
    assert "schema file not found" in capsys.readouterr().err


# --- schema module -----------------------------------------------------------

def test_schema_paths():
    assert schema.schema_path("fsm", SCHEMA_DIR).endswith(
        "fsm-0.3.0.schema.json")
    assert schema.schema_path("codec", SCHEMA_DIR).endswith(
        "codec-map-0.3.0.schema.json")
    with pytest.raises(Yaml2cError):
        schema.schema_path("recipe", SCHEMA_DIR)
    with pytest.raises(Yaml2cError):
        schema.schema_path("fsm", "nowhere")


def test_load_schema():
    document = schema.load_schema("fsm", SCHEMA_DIR)
    assert document["$id"].endswith("fsm-0.3.0.schema.json")


def test_validate_document_passes_and_fails(fsm_file):
    from tools.yaml2c.common import loader_view
    from tools.yaml2c.yaml2c import compose_document

    view = loader_view(compose_document(str(fsm_file)))
    assert schema.validate_document(view, "fsm", str(SCHEMA_DIR),
                                    "doc.yaml") is None
    view["schema_version"] = "9.9.9"
    with pytest.raises(Yaml2cError) as info:
        schema.validate_document(view, "fsm", str(SCHEMA_DIR), "doc.yaml")
    assert "doc.yaml violates fsm-0.3.0.schema.json" in str(info.value)


def test_validate_document_without_jsonschema(fsm_file, monkeypatch):
    """The gate refuses loudly when jsonschema is absent (fail closed):
    generating unchecked C would replace the runtime loader's checks."""
    import sys

    from tools.yaml2c.common import loader_view
    from tools.yaml2c.yaml2c import compose_document

    monkeypatch.setitem(sys.modules, "jsonschema", None)
    view = loader_view(compose_document(str(fsm_file)))
    with pytest.raises(Yaml2cError) as info:
        schema.validate_document(view, "fsm", str(SCHEMA_DIR))
    assert "jsonschema" in str(info.value)


def test_cli_empty_document_exits_one(tmp_path, capsys):
    empty = tmp_path / "empty.yaml"
    empty.write_text("", encoding="utf-8")
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(empty)]) == 1
    assert "not a mapping" in capsys.readouterr().err


def test_cli_multi_document_yaml_exits_one(tmp_path, capsys):
    multi = tmp_path / "multi.yaml"
    multi.write_text("schema_version: \"0.3.0\"\n---\nstate_machines: []\n",
                     encoding="utf-8")
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(multi)]) == 1
    assert "YAML syntax error" in capsys.readouterr().err


def test_cli_directory_input_exits_two(tmp_path, capsys):
    assert cli.main([str(tmp_path)]) == 2
    assert "yaml2c: error:" in capsys.readouterr().err


def test_cli_codec_document_stdout(tmp_path, capsys):
    doc = tmp_path / "map.yaml"
    doc.write_text("""
schema_version: "0.3.0"
codec_map:
  name: m
  version: 1.0.0
  messages:
    - id: 1
      name: M
      dlc: 1
      signals:
        - name: b
          start_bit: 0
          bit_length: 1
          type: boolean
          endianness: little
""", encoding="utf-8")
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(doc)]) == 0
    assert "MAP_CODEC_MAP_H" in capsys.readouterr().out


def test_cli_control_character_yaml_exits_one(tmp_path, capsys):
    """A NUL byte is valid UTF-8 but rejected by the YAML reader."""
    bad = tmp_path / "nul.yaml"
    bad.write_bytes(b"a: \x00\n")
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(bad)]) == 1
    assert "YAML syntax error" in capsys.readouterr().err


def test_cli_non_utf8_input_exits_one(tmp_path, capsys):
    bad = tmp_path / "binary.yaml"
    bad.write_bytes(b"a: \xff\xfe\n")
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(bad)]) == 1
    assert "not valid UTF-8" in capsys.readouterr().err


def test_cli_open_race_exits_two(tmp_path, fsm_file, capsys, monkeypatch):
    """The file passes the existence check but cannot be opened (the
    classic check-then-open race): report a clean usage error."""
    import tools.yaml2c.yaml2c as module

    real_isfile = module.os.path.isfile

    monkeypatch.setattr(module.os.path, "isfile",
                        lambda path: True if path == str(fsm_file)
                        else real_isfile(path))
    import builtins

    real_open = builtins.open

    def fake_open(path, *args, **kwargs):
        if str(path) == str(fsm_file):
            raise IsADirectoryError(21, "Is a directory", str(path))
        return real_open(path, *args, **kwargs)

    monkeypatch.setattr(builtins, "open", fake_open)
    assert cli.main(["--schema-dir", str(SCHEMA_DIR), "--stdout",
                     str(fsm_file)]) == 2
    assert "yaml2c: error:" in capsys.readouterr().err
